// Color palette variants for the 4-phase sunset transition.
// Each palette defines colors at 4 keyframes (golden, twilight, blue, darkness).
// Colors are interpolated smoothly between keyframes.

export const lightingVariants = {
  warmDominant: {
    id: 'warmDominant',
    label: 'Warm dominant',
    phases: {
      golden: {
        ambient: '#f5c842',
        ambientIntensity: 0.15,
        backlight: '#f5c842',
        skyTop: '#f5c842',
        skyBottom: '#c44b6c',
        sunLineOpacity: 1.0,
      },
      twilight: {
        ambient: '#c44b6c',
        ambientIntensity: 0.08,
        backlight: '#c44b6c',
        skyTop: '#5a3b8a',
        skyBottom: '#c44b6c',
        sunLineOpacity: 0.3,
      },
      blue: {
        ambient: '#3a2a5a',
        ambientIntensity: 0.05,
        backlight: '#1a1050',
        skyTop: '#0a0a20',
        skyBottom: '#1a1a2e',
        sunLineOpacity: 0,
      },
      darkness: {
        ambient: '#050510',
        ambientIntensity: 0.01,
        backlight: '#050510',
        skyTop: '#000000',
        skyBottom: '#000000',
        sunLineOpacity: 0,
      },
    },
  },
  coolDominant: {
    id: 'coolDominant',
    label: 'Cool dominant',
    phases: {
      golden: {
        ambient: '#e8a860',
        ambientIntensity: 0.5,
        backlight: '#d4944c',
        skyTop: '#d4bfa0',
        skyBottom: '#c87830',
        sunLineOpacity: 0.8,
      },
      twilight: {
        ambient: '#9060a0',
        ambientIntensity: 0.3,
        backlight: '#7040a0',
        skyTop: '#4a1a6a',
        skyBottom: '#a03060',
        sunLineOpacity: 0.15,
      },
      blue: {
        ambient: '#1a1560',
        ambientIntensity: 0.15,
        backlight: '#0a0a40',
        skyTop: '#050515',
        skyBottom: '#0a0a30',
        sunLineOpacity: 0,
      },
      darkness: {
        ambient: '#080810',
        ambientIntensity: 0.02,
        backlight: '#030308',
        skyTop: '#000000',
        skyBottom: '#000003',
        sunLineOpacity: 0,
      },
    },
  },
  natural: {
    id: 'natural',
    label: 'Natural / documentary',
    phases: {
      golden: {
        ambient: '#d4a870',
        ambientIntensity: 0.5,
        backlight: '#c09050',
        skyTop: '#c8b89a',
        skyBottom: '#b08040',
        sunLineOpacity: 0.6,
      },
      twilight: {
        ambient: '#a07068',
        ambientIntensity: 0.25,
        backlight: '#806058',
        skyTop: '#5a3040',
        skyBottom: '#905040',
        sunLineOpacity: 0.1,
      },
      blue: {
        ambient: '#253050',
        ambientIntensity: 0.12,
        backlight: '#152038',
        skyTop: '#0a0a18',
        skyBottom: '#101828',
        sunLineOpacity: 0,
      },
      darkness: {
        ambient: '#0a0a10',
        ambientIntensity: 0.02,
        backlight: '#050508',
        skyTop: '#000000',
        skyBottom: '#000003',
        sunLineOpacity: 0,
      },
    },
  },
  sodiumVapor: {
    id: 'sodiumVapor',
    label: 'Sodium vapor',
    phases: {
      golden: {
        ambient: '#ffaa00',
        ambientIntensity: 0.8,
        backlight: '#ff9900',
        skyTop: '#ffcc44',
        skyBottom: '#ff8800',
        sunLineOpacity: 1.0,
      },
      twilight: {
        ambient: '#cc7700',
        ambientIntensity: 0.4,
        backlight: '#aa5500',
        skyTop: '#aa6600',
        skyBottom: '#884400',
        sunLineOpacity: 0.5,
      },
      blue: {
        ambient: '#553300',
        ambientIntensity: 0.1,
        backlight: '#331a00',
        skyTop: '#221100',
        skyBottom: '#1a0d00',
        sunLineOpacity: 0.1,
      },
      darkness: {
        ambient: '#110800',
        ambientIntensity: 0.02,
        backlight: '#0a0400',
        skyTop: '#050200',
        skyBottom: '#030100',
        sunLineOpacity: 0,
      },
    },
  },
  prismaticShift: {
    id: 'prismaticShift',
    label: 'Prismatic shift',
    phases: {
      golden: {
        ambient: '#ff4444',
        ambientIntensity: 0.5,
        backlight: '#ff2222',
        skyTop: '#ff6666',
        skyBottom: '#cc2222',
        sunLineOpacity: 0.6,
      },
      twilight: {
        ambient: '#44ff44',
        ambientIntensity: 0.4,
        backlight: '#22cc22',
        skyTop: '#66ff66',
        skyBottom: '#22aa22',
        sunLineOpacity: 0.3,
      },
      blue: {
        ambient: '#4444ff',
        ambientIntensity: 0.3,
        backlight: '#2222cc',
        skyTop: '#3333aa',
        skyBottom: '#1a1a88',
        sunLineOpacity: 0.1,
      },
      darkness: {
        ambient: '#110022',
        ambientIntensity: 0.03,
        backlight: '#080011',
        skyTop: '#050008',
        skyBottom: '#030005',
        sunLineOpacity: 0,
      },
    },
  },
}

export const lightingVariantList = Object.values(lightingVariants)
